### ISSUE TITLE
Can't join zoom by id,only url

### ISSUE THREAD

**Issue by tanghaoran666** [lukdiekm/zoom-with-alfred#5]
I find this workflow can't join zoom bu meetingId,Only Meetingurl.
I think maybe cause this line in saveRoom.sh can't parse meetingId.
If i input meetingId ,it will output nothing after this convert.

![企业微信截图_c2e3c70d-079a-4619-9546-43d174fe8267_副本](https://user-images.githubusercontent.com/39946578/219618474-6a4afd37-535c-44e5-8cdc-6845acf4cf9c.jpg)

**Comment by lukdiekm** [comment]
thanks for the fix @tanghaoran666. pr has been merged.
